#version: '3.8' plus besoin de spécifier la version
services:
  server:
    image: nginx:latest
    ports:
      - 8080:80
      - 443:443
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    #networks:
      #- your_network



  backend:
    container_name: back
    build:
      #dockerfile: Dockerfile
      context: "./backend"

    env_file: ./backend/.env

    volumes:
      - /app/node_modules
      - ./backend:/app  

    #environment:
      #DATABASE_URL: mysql://dbuser:dbpassword@mysql_db/utopid
    depends_on:
      - mysql_db
     # - server

    
    ports:
      - "4000:4000"

    #networks:
      #- your_network

    




  frontend:
    container_name: front
    stdin_open: true
    build: 
      #dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app  
    ports:
    # <port hôte> : <port container> 
      - "3000:3000"

     # - CHOKIDAR_USEPOLLING=true
     # NODE_ENV=development
    depends_on:
       #- server
       - backend

    #networks:
     # - your_network



  mysql_db:
    image: mysql:8.0
    restart: always

    env_file: 
      - ./backend/.env # on importe les variables d'environnement dans le container 

    #environment:
  
      #DATABASE_URL: mysql://dbuser:dbpassword@mysql_db/utopid

    ports:
      - "3306:3306"

    volumes:
      - ./mysql:/var/lib/mysql
      - ./db-config/init.sql:/docker-entrypoint-initdb.d/init.sql

    #depends_on:
     # - server

    

#networks:
  #your_network:
    #driver: bridge




  
