#version: '3.8'
services:
  server:
    image: nginx:latest
  #  ports:
   #   - 80:80

    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx



  backend:
    container_name: back
    build:
      #dockerfile: Dockerfile
      context: "./backend"

    env_file: ./backend/.env

    volumes:
      - /app/node_modules
      - ./backend:/app  
    depends_on:
      - mysql_db
      - server
    environment:
      
      - NODE_ENV=development
    ports:
      - "4000:4000"

    




  frontend:
    container_name: front
    stdin_open: true
    build: 
      #dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app  
    ports:
    # <port hôte> : <port container> 
      - "3000:3000"
    environment:
     # - CHOKIDAR_USEPOLLING=true
       - NODE_ENV=development
    depends_on:
       #- server
       - backend



  mysql_db:
    image: mysql:latest
    restart: always
    env_file: 
      - ./backend/.env # on importe les variables d'environnement dans le container 

    ports:
      - "3307:3307"

    volumes:
      - ./mysql:/var/lib/mysql





      
