#FROM nginx:latest

#COPY ./default.conf /etc/nginx/conf.d/default.conf


#EXPOSE 4000


#image node
FROM node:22.7

#pointage vers mon dossier virtuel /server  crée par WORKDIR
WORKDIR /app

#je copie tous les fichiers qui commencent par package* à la  racine du dossier app de docker c'est à dire /app
COPY package*.json ./

#installer node
# Installing dependencies.
RUN npm i -g nodemon

#dépendances
RUN npm i dotenv --save 


RUN npm i

COPY . .




#les commandes utilisés dans package json et par default
CMD [ "npm","run", "dev"]

#tu écoute le port 4000
EXPOSE 4000







